import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/home-page/header";
import { getAuth } from "../actions/auth";
import GetLikedMovies from "../components/liked-movies/get-liked-movies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await getAuth();
  return (
    <html lang="en">
      <body className={inter.className}>
      <GetLikedMovies />
        <Header auth={auth} />
        {children}
      </body>
    </html>
  );
}
